


function playOne() {
	let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let move = document.querySelector("#my-divone");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 100);
	let font = parseInt(Math.random() * 100);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	move.innerHTML = numbers;
	move.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";
 	// move.style["background-color"] = "#" + colors;
 	move.style.width = widht + "px";
 	move.style.height = widht + "px";
 	// move.style.padding = parseInt(Math.random()*100) + "px";
 	move.style["margin-left"] = widht + "px";
 	move.style["font-size"] = font + "px";
 	move.style["margin-right"] = widht + "px";
 	// move.style["margin-top"] = widht + "px";
 	// move.style["margin-bottom"] = widht + "px";
 	move.style["border-radius"] = 200 + "px";
 	move.style.transition = 2 + "s";
 	move.style.color = "#" + colr;
 	move.style["font-weight"] = "bold";
 	// move.style.border = 6 +"px" + "Solid" + "red";

}	
 	function playTwo() {
 			let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-div");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	
function playThree() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divs");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";
	
 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	function playFour() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divss");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font*w20ight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	function playFive() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divsss");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 80);
	let font = parseInt(Math.random() * 80);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	function playSix() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divsix");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";
	
 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	function playSeven() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divseven");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	function playEight() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-diveight");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 100);
	let font = parseInt(Math.random() * 100);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";
	
 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color= "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	function playNine() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divnine");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	function playTen() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divten");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}	function playEle() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divel");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";
	
 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playTwe() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divtw");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 100);
	let font = parseInt(Math.random() * 100);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playThr() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divthr");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playFou() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divfou");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 90);
	let font = parseInt(Math.random() * 90);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playFiv() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divfiv");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playSixteen() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divsixteen");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";
	
 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playSeventeen() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divseventeen");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 100);
	let font = parseInt(Math.random() * 100);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playEighteen() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-diveighteen");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playNineteen() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divninteen");
	let numbers = parseInt(Math.random() * 1000);
	let	widht = parseInt(Math.random() * 60);
	let font = parseInt(Math.random() * 60);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	moves.style["margin-right"] = widht + "px";
 	// moves.style["margin-top"] = widht + "px";
 	// moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}function playTwenty() {
		let red = parseInt(Math.random() * 255);
let green = parseInt(Math.random() * 255);
let blue = parseInt(Math.random() * 255);
// let a = (Math.random()*100);
let a = 0.79;
	let moves = document.querySelector("#my-divtwenty");
	let numbers = parseInt(Math.random() * 99);
	let	widht = parseInt(Math.random() * 30);
	let font = parseInt(Math.random() * 50);
	// let colors = parseInt(Math.random() *1000000);
	let colr = parseInt(Math.random() *1000000);
	// let bordr = parseInt(Math.random() *1000000);
	moves.innerHTML = numbers;
	moves.style["background-color"] = "rgba"+"("+red+","+green+","+blue+","+a+")";

 	// move.style["background-color"] = "#" + colors;
 	moves.style.width = widht + "px";
 	moves.style.height = widht + "px";
 	// moves.style.padding = parseInt(Math.random()*100) + "px";
 	// moves.style["margin-left"] = widht + "px";
 	moves.style["font-size"] = font + "px";
 	// move.style["margin-right"] = widht + "px";
 	moves.style["margin-top"] = widht + "px";
 	moves.style["margin-bottom"] = widht + "px";
 	moves.style["border-radius"] = 200 + "px";
 	moves.style.transition = 2 + "s";
 	moves.style.color = "#" + colr;
 	moves.style["font-weight"] = "bold";
 	// move.style.border = 3 +"px" + "Solid" + "#" + bordr;
}
// let create = document.querySelector("body");
for (let i=0; i<=100; i++) {

function play() {
	// let colr = parseInt(Math.random() *1000000);

	// let hide = document.querySelector("h1");
	// let hide2 = document.querySelector("h2");
	let sec = document.querySelector("body");
	let btn = document.querySelector("button");
	// let innerRound = document.querySelector("");
	// innerRound.style.border = 7 + "px" +" "+ "solid" +" "+ "Red";
	// hide.style["z-index"] = "1";
	// hide2.style["z-index"] = "1";
	// hide.style.position = "absolute";
	// hide2.style.position = "absolute";
	// hide.style.display = "none";
	// hide2.style.display = "none";

	// let colr = parseInt(Math.random() *100);
 	// innerRound.style["background-color"] = "#"+colr+colr+colr;
 	// btn.style["background-color"] = "#"+colr+colr+colr;
 	// btn.style.color = "#" + colr + 1000;
	// sec.style["background-color"]
	playOne();
	playTwo();
	playThree();
	playFour();
	playFive();
	playSix();
	playSeven();
	playEight();
	playNine();
	playTen();
	playEle();
	playTwe();
	playThr();
	playFou();
	playFiv();
	playSixteen();
	playSeventeen();
	playEighteen();
	playNineteen();
	playTwenty();

	// let arrryy = ["playOne()","playTwo()","playThree()","playFour()","playFive()","playSix()","playSeven()","playEight()","playNine()","playTen()","playEle()","playTwe()","playThr()","playFou()","playFiv()","playSixteen()","playSeventeen()","playEighteen()","playNineteen()","playTwenty()"];
	// let foot = (Math.random()*1000);
	// let footr = document.querySelector("footer");
	// for (let i=0; i<=foot; i++) {
	// 	footr.innerHTML = i;
	// }
	// let bordr = document.querySelector(".flex");
	// bordr.style["background-color"] = colr;
// // let big = document.querySelector("#big-div");
// //  for (let i=0; i<=arrryy.length; i++) {
// // let create = document.querySelector("body");

// //  	create.innerHTML += "<div id='big-div'>"+i+"</div>";
// //  }
// for (let i=0; i<=arrryy.length; i++) {
//   let move = document.querySelector("body");
//   move.innerHTML += [i];
// }
}
}

setInterval(play,1000);